const container = document.querySelector("#container");
const redDiv = document.createElement("p");
const blueH3 = document.createElement("h3");
const div = document.createElement("div");
const h1 = document.createElement("h1");
const p = document.createElement("p");
redDiv.textContent = "Hey, I'm red!";
blueH3.textContent = "I'm a blue h3";
redDiv.style.color = "red";
container.appendChild(redDiv);
blueH3.style.color = "blue";
container.appendChild(blueH3);
h1.textContent = "I'm in a div";
p.textContent = "ME TOO!";
div.appendChild(h1);
div.appendChild(p);
div.style.outline = "black solid 2px";
div.style.backgroundColor = "pink";
container.appendChild(div);